MUNICIPALITY_ENCODING_FIXES = {
    "Ã\x86rÃ¸": "Ærø",
    "SÃ¸nderborg": "Sønderborg",
    "NÃ¦stved": "Næstved",
    "TÃ¸nder": "Tønder",
    "FanÃ¸": "Fanø",
    "KÃ¸ge": "Køge",
    "SolrÃ¸d": "Solrød",
    "SorÃ¸": "Sorø",
    "DragÃ¸r": "Dragør",
    "Nordfyn": "Nordfyns",
    "IshÃ¸j": "Ishøj",
    "VallensbÃ¦k": "Vallensbæk",
    "TÃ¥rnby": "Tårnby",
    "BrÃ¸ndby": "Brøndby",
    "Copenhagen": "København",
    "HÃ¸je-Taastrup": "Høje-Tåstrup",
    "RÃ¸dovre": "Rødovre",
    "HolbÃ¦k": "Holbæk",
    "Lyngby-TaarbÃ¦k": "Lyngby-Tårbæk",
    "FuresÃ¸": "Furesø",
    "HÃ¸rsholm": "Hørsholm",
    "HillerÃ¸d": "Hillerød",
    "SamsÃ¸": "Samsø",
    "HalsnÃ¦s": "Halsnæs",
    "HelsingÃ¸r": "Helsingør",
    "RingkÃ¸bing-Skjern": "Ringkøbing-Skjern",
    "Aarhus": "Århus",
    "MorsÃ¸": "Morsø",
    "LÃ¦sÃ¸": "Læsø",
    "BrÃ¸nderslev": "Brønderslev",
    "HjÃ¸rring": "Hjørring",
    "AllerÃ¸d": "Allerød",
}


DISPLAY_NAME_MAPPING = {
    "Frederiksværk-Hundested": "Halsnæs",
    "Bogense": "Nordfyns",
    "Brønderslev-Dronninglund": "Brønderslev",
}
